### ISSUE TITLE
Training flow fails in when model buyer executes contract method payForModel

### ISSUE THREAD

**Issue by GFibrizo** [DeltaML/model-buyer#41]
## Description
The model_buyer fails when creating a new model with the post_model.py script in the branch **MB-38**, more specifically when executing the contract method payForModel (from model buyer).

## To Reproduce
Steps to reproduce the behavior, follow the instructions in: [https://gist.github.com/agrojas/370c1e1ba4db5a3ac25126b4ea00e0a1](https://gist.github.com/agrojas/370c1e1ba4db5a3ac25126b4ea00e0a1)

## Stacktrace
```
cte_federated_aggregator_1  | 2019-10-15 02:20:56,365 DEBUG - http://172.20.0.6:5000 "POST /trainings HTTP/1.1" 200 5
cte_federated_aggregator_1  | 2019-10-15 02:20:56,367 INFO - Response: <Response [200]> 
cte_federated_aggregator_1  | 2019-10-15 02:20:56,368 INFO - finish process_in_background...
cte_model_buyer_1           | 2019-10-15 02:20:56,413 DEBUG - http://cte_ganache_cli:8545 "POST / HTTP/1.1" 200 None
cte_model_buyer_1           | 2019-10-15 02:20:56,414 DEBUG - Getting response HTTP. URI: http://cte_ganache_cli:8545, Method: eth_estimateGas, Response: {'id': 0, 'jsonrpc': '2.0', 'error': {'message': 'execution error: revert', 'code': -32000, 'data': {'stack': 'Error: execution error: revert\n    at /app/ganache-core.docker.cli.js:69:18800\n    at /app/ganache-core.docker.cli.js:61:657175\n    at /app/ganache-core.docker.cli.js:2:62040\n    at i (/app/ganache-core.docker.cli.js:2:77139)\n    at /app/ganache-core.docker.cli.js:37:1456280\n    at /app/ganache-core.docker.cli.js:2:184425\n    at /app/ganache-core.docker.cli.js:25:392\n    at c (/app/ganache-core.docker.cli.js:25:5516)\n    at /app/ganache-core.docker.cli.js:25:317\n    at /app/ganache-core.docker.cli.js:61:675156\n    at /app/ganache-core.docker.cli.js:2:59138\n    at o (/app/ganache-core.docker.cli.js:2:62562)\n    at /app/ganache-core.docker.cli.js:2:62040\n    at /app/ganache-core.docker.cli.js:61:668716\n    at /app/ganache-core.docker.cli.js:61:666579\n    at /app/ganache-core.docker.cli.js:61:675972', 'name': 'Error'}}}
cte_model_buyer_1           | 2019-10-15 02:20:56,415 ERROR - {'message': 'execution error: revert', 'code': -32000, 'data': {'stack': 'Error: execution error: revert\n    at /app/ganache-core.docker.cli.js:69:18800\n    at /app/ganache-core.docker.cli.js:61:657175\n    at /app/ganache-core.docker.cli.js:2:62040\n    at i (/app/ganache-core.docker.cli.js:2:77139)\n    at /app/ganache-core.docker.cli.js:37:1456280\n    at /app/ganache-core.docker.cli.js:2:184425\n    at /app/ganache-core.docker.cli.js:25:392\n    at c (/app/ganache-core.docker.cli.js:25:5516)\n    at /app/ganache-core.docker.cli.js:25:317\n    at /app/ganache-core.docker.cli.js:61:675156\n    at /app/ganache-core.docker.cli.js:2:59138\n    at o (/app/ganache-core.docker.cli.js:2:62562)\n    at /app/ganache-core.docker.cli.js:2:62040\n    at /app/ganache-core.docker.cli.js:61:668716\n    at /app/ganache-core.docker.cli.js:61:666579\n    at /app/ganache-core.docker.cli.js:61:675972', 'name': 'Error'}}
cte_model_buyer_1           | 2019-10-15 02:20:56,415 ERROR - Exception on /models [POST]
cte_model_buyer_1           | Traceback (most recent call last):
cte_model_buyer_1           |   File "/root/.local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
cte_model_buyer_1           |     rv = self.dispatch_request()
cte_model_buyer_1           |   File "/root/.local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
cte_model_buyer_1           |     return self.view_functions[rule.endpoint](**req.view_args)
cte_model_buyer_1           |   File "/root/.local/lib/python3.7/site-packages/flask_restplus/api.py", line 325, in wrapper
cte_model_buyer_1           |     resp = resource(*args, **kwargs)
cte_model_buyer_1           |   File "/root/.local/lib/python3.7/site-packages/flask/views.py", line 88, in view
cte_model_buyer_1           |     return self.dispatch_request(*args, **kwargs)
cte_model_buyer_1           |   File "/root/.local/lib/python3.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
cte_model_buyer_1           |     resp = meth(*args, **kwargs)
cte_model_buyer_1           |   File "/root/.local/lib/python3.7/site-packages/flask_restplus/marshalling.py", line 136, in wrapper
cte_model_buyer_1           |     resp = f(*args, **kwargs)
cte_model_buyer_1           |   File "/app/model_buyer/resources/models_resource.py", line 113, in post
cte_model_buyer_1           |     user=user), 200
cte_model_buyer_1           |   File "/app/model_buyer/services/model_buyer_service.py", line 68, in make_new_order_model
cte_model_buyer_1           |     payment_requirements=payment_requirements["pay_for_model"])
cte_model_buyer_1           |   File "/app/model_buyer/services/contract_service.py", line 23, in pay_for_model
cte_model_buyer_1           |     self.build_contract_api(model_buyer_account).pay_for_model(model_id=model_id, pay=5)
cte_model_buyer_1           |   File "/root/.local/lib/python3.7/site-packages/commons/web3/delta_contracts.py", line 71, in pay_for_model
cte_model_buyer_1           |     self._contract.functions.payForModel(model_id, pay).transact({'from': self.address, 'value': pay})
cte_model_buyer_1           |   File "/root/.local/lib/python3.7/site-packages/web3/contract.py", line 878, in transact
cte_model_buyer_1           |     **self.kwargs
cte_model_buyer_1           |   File "/root/.local/lib/python3.7/site-packages/web3/contract.py", line 1439, in transact_with_contract_function
cte_model_buyer_1           |     txn_hash = web3.eth.sendTransaction(transact_transaction)
cte_model_buyer_1           |   File "/root/.local/lib/python3.7/site-packages/web3/eth.py", line 306, in sendTransaction
cte_model_buyer_1           |     get_buffered_gas_estimate(self.web3, transaction),
cte_model_buyer_1           |   File "/root/.local/lib/python3.7/site-packages/web3/_utils/transactions.py", line 95, in get_buffered_gas_estimate
cte_model_buyer_1           |     gas_estimate = web3.eth.estimateGas(gas_estimate_transaction)
cte_model_buyer_1           |   File "/root/.local/lib/python3.7/site-packages/web3/eth.py", line 362, in estimateGas
cte_model_buyer_1           |     params,
cte_model_buyer_1           |   File "/root/.local/lib/python3.7/site-packages/web3/manager.py", line 97, in request_blocking
cte_model_buyer_1           |     raise ValueError(response["error"])
cte_model_buyer_1           | ValueError: {'message': 'execution error: revert', 'code': -32000, 'data': {'stack': 'Error: execution error: revert\n    at /app/ganache-core.docker.cli.js:69:18800\n    at /app/ganache-core.docker.cli.js:61:657175\n    at /app/ganache-core.docker.cli.js:2:62040\n    at i (/app/ganache-core.docker.cli.js:2:77139)\n    at /app/ganache-core.docker.cli.js:37:1456280\n    at /app/ganache-core.docker.cli.js:2:184425\n    at /app/ganache-core.docker.cli.js:25:392\n    at c (/app/ganache-core.docker.cli.js:25:5516)\n    at /app/ganache-core.docker.cli.js:25:317\n    at /app/ganache-core.docker.cli.js:61:675156\n    at /app/ganache-core.docker.cli.js:2:59138\n    at o (/app/ganache-core.docker.cli.js:2:62562)\n    at /app/ganache-core.docker.cli.js:2:62040\n    at /app/ganache-core.docker.cli.js:61:668716\n    at /app/ganache-core.docker.cli.js:61:666579\n    at /app/ganache-core.docker.cli.js:61:675972', 'name': 'Error'}}

```

**Comment by GFibrizo** [comment]
Fixes in
https://github.com/DeltaML/model-buyer/pull/42
https://github.com/DeltaML/federated-aggregator/pull/23

**Comment by agrojas** [comment]
Add contract [PR](https://github.com/DeltaML/contract/pull/5)
